services:
  - type: web
    name: smartstockwms
    runtime: node
    plan: free
    rootDirectory: backend
    buildCommand: npm install
    startCommand: node init-db.js && node import-data.js && node index.js
    envVars:
      - key: DATABASE_URL
        sync: false
